playwright: install Japanese font in Ubuntu image
themoeway/yomitan pull request #110
Opened 2023-03-26 18:56 UTC by xy2iii

By default CJK fonts are not installed on the Ubuntu image, which led to characters not displaying on the screenshot diffing tests.

![image](https://user-images.githubusercontent.com/14931040/227797800-5097a20e-955f-4ded-bbf7-6d63db771260.png)

2023-03-26 21:37 UTC, Aquafina-water-bottle submitted a review, later dismissed

2023-03-26 22:42 UTC, djahandarie approved these changes

2023-03-26 22:51 UTC, djahandarie requested changes
The action failed. 🥲 Also maybe look into https://github.com/marketplace/actions/cache-apt-packages (if you do use it please pin it at a specific hash)

2023-04-02 03:34 UTC, djahandarie approved these changes
LGTM. The playwright diff was too big so the playwright comment failed to post, but looking at the report artifact, it does exactly what we would hope (shows all the Japanese text in Japanese).

2023-04-02 03:34 UTC, merged