Whole word scanning
themoeway/yomitan pull request #1330
Opened 2024-08-21 19:25 UTC by jamesmaa

2024-08-22 17:46 UTC, jamesmaa commented on ext/js/background/backend.js
> +        if (text === null) { return false; }
Idk why I had to add this otherwise there are errors

2024-08-22 17:46 UTC, jamesmaa commented on ext/js/dom/text-source-generator.js
Irrelevant typo changes here.

2024-08-22 17:46 UTC, jamesmaa commented on types/ext/dom-text-scanner.d.ts
This formatting of comments allows me to show the jsdoc comments when I hover over `ElementSeekInfo` variables. Was helpful for me to understand the code and I suggest we do more of these in the future.

2024-08-22 18:00 UTC, jamesmaa commented on ext/js/background/backend.js
> +        if (text === null) { return false; }
okay it's gone after changes. idk what the original issue was. removing...

2024-08-22 18:25 UTC, Kuuuube reviewed
Is there any upper bound for how long a word is/how far backwards it can seek? I'm not seeing anything and this could lead to quite a lot of trouble if a user tries to scan an enormous string. Even a huge limit like 1000 characters would probably be a good idea.

2024-08-22 18:28 UTC, jamesmaa commented
@Kuuuube it uses `this._scanLength` as the max limit for looking back. Basically it tells yomitan to try to set the startOffset back by `this._scanLength` characters and indicates for it to stop going back if it sees a whitespace. 

Reference
https://github.com/themoeway/yomitan/pull/1330/files#diff-255481c4f025ab785ed8746ef13607c1fcf4ad6fc4e7ee7aecd69a25244bf992R474

2024-08-22 18:46 UTC, Kuuuube requested changes
Looks good, will approve when tests are fixed. `test/options-util.test.js` needs the version bumped from 50 to 51.

2024-08-22 18:53 UTC, Kuuuube approved these changes

2024-08-22 19:27 UTC, Kuuuube commented
Might want to have it pull the sentence termination characters and break on any of them. Though there is also the issue of should it stop on `'` because some words contain `'` but it could also be used to quote things.

2024-08-22 19:32 UTC, Casheeew commented
> Probably seeking back into other HTML elements and concatenating. Layout-aware scanning doesn't seem to impact it. 

Might be the same or similar issue to what i demonstrated on discord.

2024-08-22 19:40 UTC, Casheeew commented
> Might want to have it pull the sentence termination characters and break on any of them. Though there is also the issue of should it stop on `'` because some words contain `'` but it could also be used to quote things.

I think it's safe to just look one character before the quote and break if it's a whitespace, and not otherwise.

2024-08-24 03:52 UTC, Casheeew commented
It now works on double quoted words but not on single quoted words.

2024-08-24 03:54 UTC, Casheeew commented
Otherwise lgtm

2024-08-24 05:56 UTC, jamesmaa commented
Okay done I followed your advice and peeked at the character before the single quotes to see if it's an apostrophe or wrapped in single quotes

2024-08-24 07:21 UTC, Casheeew approved these changes

2024-08-24 14:49 UTC, merged