refactored onKeyDown to be easier to read, and added test
themoeway/yomitan pull request #943
Opened 2024-05-15 01:20 UTC by brandonrainey

#918 

Changed the onKeyDown function in search-display-controller to be easier to read. Also created a new test file to test preserved behavior between the current and new function. 

The test passes, but I'm not sure if the test is up to par or not, but I tried to replicate as well as I could figure out how to.

2024-05-15 01:26 UTC, Kuuuube commented
Add this to the tests:
```
ctrl + a
alt + a
meta + a
backspace
ctrl + backspace
arrow key down
```

2024-05-15 12:01 UTC, jamesmaa reviewed
Thanks for doing this 😄 

My biggest concern stems from replicating the `search-display-controller` logic in the tests because even though they verify the correctness of the current yomitan, if the logic of those if statement changes in the future, we would need to update the corresponding tests, which I don't expect future developers to remember to do.

2024-05-15 21:40 UTC, brandonrainey commented on test/search-display-controller.test.js
> +function onKeyDownNew(e) {
I originally tried to make an instance of SearchDisplayController in the test, but I have to import every dependency and its dependencies and so on, which seems like a lot. I've also tried some other ways but nothing has seemed to work to grab the function.

2024-05-16 03:23 UTC, jamesmaa commented on test/search-display-controller.test.js
> +function onKeyDownNew(e) {
I'm fine ignoring the eslint error

2024-05-16 03:28 UTC, jamesmaa commented on test/search-display-controller.test.js
> +    test('should test that onKeyDownCurrent function focuses input', () => {
btw I feel like we should include one or two tests that test the negative condition.

For example, if `onKeyDown`'s logic is 
```js
function onKeyDown(e){
    if (true) {
        queryInput.focus({preventScroll: true});
    }
}
```

Then these tests would pass even though it's wrong

2024-05-17 02:20 UTC, Kuuuube requested changes
It would also be good to include this test in the package.json. Maybe something like this:

```json
"test:onkeydown": "vitest run --config test/data/vitest.search-display-controller.config.json",
```

With `test/data/vitest.search-display-controller.config.json` looking like this:
```json
{
    "test": {
        "include": [
            "test/search-display-controller.test.js"
        ]
    }
}
```

Then `npm run test:search-display-controller` can be added to `"test"` command in package.json as well.

2024-05-17 02:20 UTC, Kuuuube commented on test/search-display-controller.test.js
> +        new KeyboardEvent('keydown', {key: 'Backspace'})
```suggestion
        new KeyboardEvent('keydown', {key: 'Backspace'}),
        new KeyboardEvent('keydown', {key: 'Backspace', ctrlKey: true, metaKey: false, altKey: false})
```

2024-05-17 02:20 UTC, Kuuuube commented on ext/js/display/search-display-controller.js
> +        if (!isInputField && !isModifierKey && isAllowedKey && !isSpaceKey) {
Suggestion for how to handle the ctrl + backspace case. Feel free to disregard if you have a better idea.
```suggestion
        const isCtrlBackspace = e.ctrlKey && e.key === 'Backspace';
        const isModifierKey = e.ctrlKey || e.metaKey || e.altKey;
        const isSpaceKey = e.key === ' ';

        if (!isInputField && (!isModifierKey || isCtrlBackspace) && isAllowedKey && !isSpaceKey) {
```

2024-05-17 02:45 UTC, Kuuuube commented
Actually disregard the part about adding a specific script for this in the package. It's probably not important enough to need that. It runs with `test:js` anyways.

2024-05-17 03:02 UTC, Kuuuube approved these changes
Thank you for taking the time to add this!

2024-05-17 04:10 UTC, merged